# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - boston-house-price-prediction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://siddmirjankpredictionapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_12f60b9ca2644331b8e2b11c646a0851 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fa9598e23c914b75bfc0b6abf5e7c9d2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: siddmirjankpredictionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_12f60b9ca2644331b8e2b11c646a0851 }}/boston-house-price-prediction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'boston-house-price-prediction'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7af4e36befca431fa486ed95233c3da0 }}
        images: 'siddmirjankpredictionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_12f60b9ca2644331b8e2b11c646a0851 }}/boston-house-price-prediction:${{ github.sha }}'